// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNNDataContext.Context;

namespace NNNDataContext.Migrations
{
    [DbContext(typeof(NewsContext))]
    partial class NewsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NNNDataModel.Log.UserLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime");

                    b.Property<int>("EventId");

                    b.Property<string>("EventName");

                    b.Property<string>("LocalIPAddress");

                    b.Property<string>("Message");

                    b.Property<int>("Priority");

                    b.Property<string>("RemoteIPAddress");

                    b.Property<string>("Source");

                    b.Property<string>("TraceId");

                    b.Property<DateTime?>("UpdatedTime");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("NNNDataModel.Log.UserTraceLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("HasPaylod");

                    b.Property<string>("LocalIPAddress");

                    b.Property<string>("Message");

                    b.Property<string>("PayloadBlob");

                    b.Property<string>("RemoteIPAddress");

                    b.Property<string>("Source");

                    b.Property<string>("TraceId");

                    b.Property<DateTime?>("UpdatedTime");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Traces");
                });

            modelBuilder.Entity("NNNDataModel.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Link");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdatedTime");

                    b.HasKey("ID");

                    b.ToTable("News");
                });
#pragma warning restore 612, 618
        }
    }
}
