on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_nbc-news-now:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ 'd978bb76-25ad-4177-a491-22ac67a5e6ca' }}
        APP_NAME: ${{ 'nbc-news-now' }}
      run: |
        cd ./ASPNetCoreLabs/HerokuContainer
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
