on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_nbc-news-now:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_USERNAME: ${{ 'yo.yasinozturk@gmail.com' }}
        HEROKU_API_KEY: ${{ 'd978bb76-25ad-4177-a491-22ac67a5e6ca' }}
        APP_NAME: ${{ 'nbc-news-now' }}
      run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag NBCNewsNow registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
